#!/bin/bash
# Script de diagnóstico para el error 404 en /api/token/

echo "🔍 DIAGNÓSTICO DEL ERROR 404 EN API"
echo "==================================="
echo ""

echo "✅ PROGRESO CONFIRMADO:"
echo "   - Mixed Content Error: RESUELTO ✅"
echo "   - HTTPS funcionando: ✅" 
echo "   - Frontend conecta con API via HTTPS: ✅"
echo ""

echo "❌ PROBLEMA ACTUAL:"
echo "   - Error: POST https://www.sanchodistribuidora.com/api/token/ 404 (Not Found)"
echo "   - Causa: El backend no responde en la ruta /api/token/"
echo ""

echo "🔧 POSIBLES CAUSAS:"
echo "   1. El middleware stripprefix no está funcionando correctamente"
echo "   2. El backend no está corriendo en el puerto 8030"  
echo "   3. La ruta /token/ no existe en el backend Django"
echo "   4. Configuración de routing en Traefik incorrecta"
echo ""

echo "🎯 PASOS PARA RESOLVER:"
echo ""
echo "1. Verificar contenedores ejecutándose:"
echo "   ssh root@168.231.67.221 'docker ps | grep maestro'"
echo ""
echo "2. Verificar logs del backend:"
echo "   ssh root@168.231.67.221 'docker logs maestro_backend_api --tail 20'"
echo ""
echo "3. Probar API directamente (sin Traefik):"
echo "   ssh root@168.231.67.221 'curl -X POST http://localhost:8030/token/ -H \"Content-Type: application/json\"'"
echo ""
echo "4. Verificar routing de Traefik:"
echo "   ssh root@168.231.67.221 'docker logs maestro_traefik | grep backend'"
echo ""
echo "5. Comprobar archivo docker-compose activo:"
echo "   ssh root@168.231.67.221 'head -20 docker-compose.yml'"
echo ""

echo "🚀 SOLUCIÓN RÁPIDA:"
echo "   El problema es de configuración del backend routing."
echo "   Necesitamos verificar que el middleware stripprefix"
echo "   esté enviando las peticiones correctamente al backend."
echo ""
echo "==================================="
