services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maestro_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8030"
    volumes:
      - .:/app
    ports:
      - "8030:8030"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build:
      context: ./dbackf
      dockerfile: Dockerfile
    container_name: maestro_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://168.231.67.221:8030/api/
    depends_on:
      - backend
  db:
    image: postgres:15
    container_name: maestro_db
    environment:
      POSTGRES_DB: maestro
      POSTGRES_USER: maestro
      POSTGRES_PASSWORD: maestro
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
volumes:
  postgres_data:
