services:
  db:
    image: postgres:15
    container_name: sanchobd-2y0ssb.1.xjngxaq8kjrzwsnuq6i97cwep
    restart: unless-stopped
    environment:
      - POSTGRES_DB=maestro_inventario
      - POSTGRES_USER=maestro
      - POSTGRES_PASSWORD=maestro
    networks:
      - dokploy-network
    # Puerto 5432 no expuesto externamente por seguridad
    # ports:
    #   - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sancho_backend_v2
    restart: always
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_NAME=maestro_inventario
      - DATABASE_USER=maestro
      - DATABASE_PASSWORD=maestro
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=www.sanchodistribuidora.com,sanchodistribuidora.com,localhost,127.0.0.1
      - SECRET_KEY=inventario-maestro-inventario-secret-key-123456789abcdef
      - DJANGO_SETTINGS_MODULE=maestro_inventario_backend.settings
      - PYTHONUNBUFFERED=1
    networks:
      - dokploy-network
    # Puerto 8030 no expuesto directamente, solo a través de Traefik
    # ports:
    #   - "8030:8030"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sancho-backend.rule=Host(`www.sanchodistribuidora.com`,`sanchodistribuidora.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sancho-backend.entrypoints=websecure"
      - "traefik.http.routers.sancho-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.sancho-backend.loadbalancer.server.port=8030"
    command: sh -c "python manage.py collectstatic --noinput && gunicorn maestro_inventario_backend.wsgi:application --bind 0.0.0.0:8030 --workers 3 --timeout 120"

  frontend:
    build: ./dbackf
    container_name: sancho_frontend_v2
    restart: unless-stopped
    networks:
      - dokploy-network
    # Puertos no expuestos directamente, solo a través de Traefik
    # ports:
    #   - "80:80"
    #   - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sancho-frontend.rule=Host(`www.sanchodistribuidora.com`,`sanchodistribuidora.com`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.sancho-frontend.entrypoints=websecure"
      - "traefik.http.routers.sancho-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.sancho-frontend.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true