services:
  db:
    image: postgres:15
    container_name: sancho-distribuidora-maestroinventario-sisuvw
    restart: unless-stopped
    environment:
      - POSTGRES_DB=maestro_inventario
      - POSTGRES_USER=maestro
      - POSTGRES_PASSWORD=maestro
    networks:
      - maestro_network
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sancho_backend_v2
    restart: always
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_NAME=maestro_inventario
      - DATABASE_USER=maestro
      - DATABASE_PASSWORD=maestro
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=www.sanchodistribuidora.com,localhost,127.0.0.1
      - SECRET_KEY=inventario-maestro-inventario-secret-key-123456789abcdef
      - DJANGO_SETTINGS_MODULE=maestro_inventario_backend.settings
      - PYTHONUNBUFFERED=1
    networks:
      - maestro_network
    ports:
      - "8030:8030"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sancho-backend.rule=Host(`www.sanchodistribuidora.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sancho-backend.entrypoints=websecure"
     # - "traefik.http.routers.sancho-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.sancho-backend.loadbalancer.server.port=8030"
      - "traefik.http.routers.sancho-backend-http.rule=Host(`www.sanchodistribuidora.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sancho-backend-http.entrypoints=web"
      - "traefik.http.routers.sancho-backend-http.service=sancho-backend"
    command: >
      sh -c "python manage.py collectstatic --noinput && gunicorn maestro_inventario_backend.wsgi:application --bind 0.0.0.0:8030 --workers 3 --timeout 120"

  frontend:
    build:
      context: ./dbackf
      dockerfile: Dockerfile
    container_name: sancho_frontend_v2
    networks:
      - maestro_network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sancho-frontend.rule=Host(`168.231.74.214`)"
      - "traefik.http.routers.sancho-frontend.entrypoints=web"
      - "traefik.http.services.sancho-frontend.loadbalancer.server.port=80"

networks:
  maestro_network:
    external: true