services:
  frontend:
    image: sancho-distribuidora-mi-front-npxvvf-frontend
    restart: unless-stopped
    networks:
      - maestro_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.sanchodistribuidora.com`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: sancho-distribuidora-mi-front-npxvvf-backend
    restart: unless-stopped
    networks:
      - maestro_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`www.sanchodistribuidora.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8030"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.sanchodistribuidora.com"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=86400"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix,cors"

networks:
  maestro_network:
    external: true