version: '3.8'

services:
  postgres_local:
    image: postgres:15
    container_name: maestro_postgres_local
    restart: unless-stopped
    environment:
      - POSTGRES_DB=maestro_inventario
      - POSTGRES_USER=maestro
      - POSTGRES_PASSWORD=maestro123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maestro -d maestro_inventario"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
