entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: tu-email@dominio.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
