# Generated by Django 5.2.4 on 2025-07-27 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_address_customer_business_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='1/1/2025 02:02:02', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
