# Generated by Django 5.2.4 on 2025-07-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='aux1',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='total',
        ),
        migrations.AddField(
            model_name='quotation',
            name='exchange',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exchange',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='exchange',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InventoryMovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('aux1', models.CharField(blank=True, max_length=255)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.inventorymovement')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productvariant')),
            ],
        ),
    ]
