# Generated by Django 5.2.4 on 2025-07-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_inventorymovement_aux1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesorder'),
        ),
    ]
