# Generated by Django 5.2.4 on 2025-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_salesorderitem_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('import', 'Importación'), ('authorize', 'Autorización'), ('RESET_PASSWORD', 'Restablecimiento de contraseña')], max_length=20),
        ),
    ]
