# Generated by Django 5.2.4 on 2025-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventorymovement_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='is_reversal',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='original_movement',
        ),
    ]
