# Generated by Django 5.2.5 on 2025-08-17 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inventorymovement_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_credit',
            field=models.BooleanField(default=False, help_text='¿El cliente tiene crédito?'),
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad_corrugado',
            field=models.IntegerField(default=0, help_text='Cantidad en corrugado', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('OFERTA', 'Oferta'), ('REMATE', 'Remate'), ('NORMAL', 'Normal')], default='NORMAL', help_text='Estado del producto', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_days',
            field=models.IntegerField(default=0, help_text='Días de crédito'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit_decimal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Límite de crédito (nuevo campo decimal)', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='has_credit',
            field=models.BooleanField(default=False, help_text='¿El proveedor maneja crédito?'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('DEPOSITO', 'Depósito Bancario')], default='TRANSFERENCIA', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia, folio, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.purchaseorder')),
            ],
            options={
                'verbose_name': 'Pago Orden de Compra',
                'verbose_name_plural': 'Pagos Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('DEPOSITO', 'Depósito Bancario')], default='EFECTIVO', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.sale')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
            },
        ),
        migrations.CreateModel(
            name='CustomerProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='core.product')),
            ],
            options={
                'verbose_name': 'Descuento Cliente-Producto',
                'verbose_name_plural': 'Descuentos Cliente-Producto',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
