# Generated by Django 5.2.5 on 2025-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_credit_days_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('NUEVO', 'Nuevo'), ('OFERTA', 'Oferta'), ('REMATE', 'Remate')], default='REGULAR', help_text='Estado del producto', max_length=10),
        ),
    ]
