# Generated by Django 5.2.5 on 2025-08-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovementdetail',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
