# Generated by Django 5.2.5 on 2025-08-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_quotation_customer_to_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
