# Generated by Django 5.2.5 on 2025-08-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_price_quotationitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_id',
            field=models.CharField(default=0.0004950495049504951, help_text='Nombre del cliente como texto libre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0004950495049504951, help_text='Precio unitario', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='core_quotation',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='core_quotationitem',
        ),
    ]
