# Generated by Django 5.2.5 on 2025-08-18 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_customer_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('DEPOSITO', 'Depósito Bancario')], default='TRANSFERENCIA', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia, folio, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-payment_date'],
            },
        ),
    ]
