# Generated by Django 5.2.4 on 2025-11-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_supplier_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
