from django.contrib import admin
from .models import User, Business, Category, Brand, Unit, Product, ProductVariant, Warehouse, ProductWarehouseStock, Supplier, SupplierProduct, PurchaseOrder, PurchaseOrderItem, PurchaseOrderReceipt, PurchaseOrderReceiptItem, InventoryMovement, CustomerType, ExchangeRate, Customer, SalesOrder, SalesOrderItem, Quotation, QuotationItem, Role, MenuOption

admin.site.register(User)
admin.site.register(Business)
admin.site.register(Category)
admin.site.register(Brand)
admin.site.register(Unit)
admin.site.register(Product)
admin.site.register(ProductVariant)
admin.site.register(Warehouse)
admin.site.register(ProductWarehouseStock)
admin.site.register(Supplier)
admin.site.register(SupplierProduct)
admin.site.register(PurchaseOrder)
admin.site.register(PurchaseOrderItem)
admin.site.register(PurchaseOrderReceipt)
admin.site.register(PurchaseOrderReceiptItem)
admin.site.register(InventoryMovement)
admin.site.register(CustomerType)
admin.site.register(ExchangeRate)
admin.site.register(Customer)
admin.site.register(SalesOrder)
admin.site.register(SalesOrderItem)
admin.site.register(Quotation)
admin.site.register(QuotationItem)
admin.site.register(Role)
admin.site.register(MenuOption)
